REW = {
# --- Pendahuluan & metodologi
"Interaksi bersifat non-linear dan berjeda waktu (Mai & Smith, 2018)": "Hubungannya tidak linear dan dampaknya muncul dengan jeda waktu (Mai & Smith, 2018)",
"Andal memproyeksikan satu atau beberapa variabel, tidak andal dalam perencanaan strategis jangka panjang yang dikendalikan oleh feedback loop (Umpan balik)": "Baik untuk memproyeksikan satu atau beberapa variabel, tetapi kurang tepat untuk perencanaan jangka panjang yang dipengaruhi feedback loop",
"Tujuan umum: mengembangkan dan memvalidasi model sistem dinamis pariwisata yang terintegrasi dengan data citra satelit untuk pemutakhiran data, guna mendukung simulasi kebijakan pariwisata di Provinsi DIY.": "Tujuan umum: mengembangkan dan memvalidasi model sistem dinamis pariwisata yang memanfaatkan citra satelit untuk memperbarui data, sebagai dasar simulasi kebijakan pariwisata di Provinsi DIY.",
"Mengembangkan model SD yang memanfaatkan citra satelit untuk memutakhirkan variabel berjeda data, lalu menguji validitas struktur dan kesesuaiannya terhadap data historis.": "Mengembangkan model SD yang memanfaatkan citra satelit untuk memperbarui variabel yang datanya terlambat tersedia, lalu menguji validitas struktur dan kesesuaiannya dengan data historis.",
"Lima stok inti: wisatawan, hotel & akomodasi, ODTW, tenaga kerja, lahan terbangun. Tanpa guncangan eksternal (pandemi, bencana, krisis), serta tanpa faktor harga, promosi, dan musim.": "Lima stok utama: wisatawan, hotel & akomodasi, ODTW, tenaga kerja, lahan terbangun. Tidak memasukkan shock eksternal (pandemi, bencana, krisis), harga, promosi, dan musim.",
"Estimator pemutakhir untuk lahan terbangun dan jumlah ODTW, bukan variabel dalam struktur model": "Dipakai untuk memperbarui data lahan terbangun dan jumlah ODTW, bukan sebagai variabel di dalam model",
"Dua tuas (insentif investasi, konservasi lahan) dengan tiga skenario yang disusun dari analisis sensitivitas dan dokumen kebijakan, tanpa lokakarya pemangku kepentingan": "Dua variabel kebijakan (insentif investasi, konservasi lahan) dan tiga skenario, disusun dari analisis sensitivitas dan dokumen kebijakan, tanpa lokakarya pemangku kepentingan",
"Patahan metode wisnus 2018→2019": "Perubahan metode pencatatan wisnus 2018→2019",
"Guncangan eksogen yang tidak dimodelkan.": "Shock dari luar yang tidak dimodelkan.",
# --- Tujuan 1
"Kontekstualisasi DIY": "Penyesuaian dengan kondisi DIY",
"Literatur substantif": "Literatur pendukung",
"Empat tingkat: variabel, hubungan kausal, feedback loop, batas model.": "Diperiksa pada empat tingkat: variabel, hubungan kausal, feedback loop, dan batas model.",
"Relevansi & definisi": "Relevan & terdefinisi jelas",
"Polaritas": "Arah hubungan (+/−)",
"Didukung teori, bukti empiris, atau identitas model yang jelas?": "Didukung teori, bukti empiris, atau definisi model yang jelas?",
"Takeaway  CLD adalah hasil adaptasi + kontekstualisasi + evaluasi, bukan salinan model rujukan; ketersediaan data dipertimbangkan saat operasionalisasi.": "Takeaway  CLD adalah hasil adaptasi, penyesuaian dengan kondisi DIY, dan evaluasi, bukan salinan model rujukan. Ketersediaan data dipertimbangkan saat model dikuantifikasi.",
"hubungan kausal dievaluasi: arah, mekanisme, dan jenis dukungan (literatur substantif vs identitas/operasionalisasi)": "hubungan kausal dievaluasi: arah, mekanisme, dan dasarnya (literatur pendukung atau definisi dalam model)",
"hubungan dibuang: Tenaga Kerja Pariwisata → pembangunan ODTW (tanpa dasar kausal memadai)": "hubungan dibuang: Tenaga Kerja Pariwisata → pembangunan ODTW (dasar sebab-akibatnya tidak cukup)",
"Identitas agregasi": "Definisi penjumlahan",
"Identitas stok-aliran; Fatina dkk.": "Persamaan stok-aliran; Fatina dkk.",
"Identitas model": "Definisi dalam model",
"Identitas stok-aliran": "Persamaan stok-aliran",
"Literatur + operasionalisasi": "Literatur + definisi model",
"Identitas kapasitas": "Definisi kapasitas",
"Identitas penyesuaian": "Definisi penyesuaian",
"Penguat": "Reinforcing",
"Penyeimbang": "Balancing",
"Jalur ekonomi–atraksi; tempat tuas Insentif Kebijakan bekerja": "Jalur ekonomi–atraksi; tempat Insentif Kebijakan bekerja",
"Rem kepadatan (crowding)": "Pembatas kepadatan (crowding)",
"Rem daya dukung lahan; tempat tuas Konservasi Lahan bekerja": "Pembatas daya dukung lahan; tempat Konservasi Lahan bekerja",
"Takeaway  Pertumbuhan didorong R1–R2 dan ditahan B1–B2; dua tuas kebijakan menempel pada R2 (insentif) dan B2 (konservasi). Hubungan TK → pembangunan ODTW tidak dipertahankan.": "Takeaway  Pertumbuhan didorong R1–R2 dan ditahan B1–B2. Dua variabel kebijakan bekerja di R2 (insentif) dan B2 (konservasi). Hubungan TK → pembangunan ODTW tidak dipakai.",
"Endogen · 26 variabel": "Dihitung di dalam model · 26 variabel",
"Eksogen · 35 parameter": "Input dari luar model · 35 parameter",
"• Karakteristik struktural akomodasi": "• Karakteristik akomodasi",
"• Dua tuas kebijakan": "• Dua variabel kebijakan",
"• Guncangan (pandemi, erupsi, gempa)": "• Shock (pandemi, erupsi, gempa)",
"Konsekuensi utama:  mekanisme penyeimbang lewat harga tidak tercakup; promosi & aksesibilitas tersirat di LPE; lintasan tanpa guncangan; daya dukung lahan cenderung longgar (luas administratif).": "Konsekuensi utama:  pengaruh harga tidak tercakup; promosi & aksesibilitas sudah termasuk dalam LPE; proyeksi tanpa shock; daya dukung lahan cenderung longgar (memakai luas wilayah).",
"Takeaway  Hasil model tidak boleh ditafsirkan pada ranah harga, promosi, musim, maupun guncangan eksternal.": "Takeaway  Hasil model tidak dapat dipakai untuk menjawab pertanyaan tentang harga, promosi, musim, maupun shock eksternal.",
"Teridentifikasi dari 6 subsistem (permintaan & daya tarik, atraksi, ekonomi & investasi, akomodasi, lahan, tenaga kerja); seluruhnya terpetakan ke statistik resmi.": "Berasal dari 6 subsistem (permintaan & daya tarik, atraksi, ekonomi & investasi, akomodasi, lahan, tenaga kerja); semuanya punya padanan statistik resmi.",
"26 endogen, 35 eksogen, 15 aspek dikeluarkan beserta konsekuensinya terhadap tafsir hasil.": "26 variabel dihitung model, 35 input dari luar model, 15 aspek dikeluarkan beserta dampaknya pada penafsiran hasil.",
# --- Citra
"Agregasi temporal": "Rata-rata per tahun",
"Agregasi spasial": "Rata-rata per wilayah",
"Rata-rata zonal seluruh piksel dalam batas DIY → satu nilai NTL per tahun.": "Rata-rata seluruh piksel di wilayah DIY → satu nilai NTL per tahun.",
"Uji kelayakan estimator": "Uji kelayakan hasil estimasi",
"Korelasi pada level dan selisih tahunan (menghindari regresi lancung akibat tren bersama), lalu LOOCV.": "Korelasi pada nilai level dan selisih tahunan (menghindari spurious regression karena tren yang sama), lalu LOOCV.",
"s galat baku sisaan; Sₓₓ jumlah kuadrat simpangan NTL. 2016 terlebar (≈ 58 unit) karena di luar rentang latih": "s standard error residual; Sₓₓ jumlah kuadrat simpangan NTL. 2016 paling lebar (≈ 58 unit) karena di luar rentang data latih",
"n₁₁, n₀₀ benar; n₁₀ komisi; n₀₁ omisi. Hasil: OA 80,50% · UA 66,00% · PA 73,58%": "n₁₁, n₀₀ benar; n₁₀ commission error; n₀₁ omission error. Hasil: OA 80,50% · UA 66,00% · PA 73,58%",
"Selisih arah NTL–ODTW terbesar pada 2021–2022 dan 2023–2024, bertepatan dengan galat LOOCV terbesar": "Perbedaan arah NTL–ODTW terbesar pada 2021–2022 dan 2023–2024, sama dengan tahun error LOOCV terbesar",
"user's accuracy kelas terbangun: komisi dominan (34 dari 100 titik)": "user's accuracy kelas terbangun: commission error dominan (34 dari 100 titik)",
"lahan terbangun 2023→2025 (75.624 → 55.030 ha): artefak, bukan perubahan fisik": "lahan terbangun 2023→2025 (75.624 → 55.030 ha): kesalahan data, bukan perubahan fisik",
"75.624 ha (2023) → 55.030 ha (2025): tidak mungkin secara fisik → artefak klasifikasi. Tahun dengan observasi tinggi (2019, 2023) juga tahun dengan luas tinggi.": "75.624 ha (2023) → 55.030 ha (2025): tidak mungkin terjadi di lapangan → kesalahan klasifikasi. Tahun dengan observasi banyak (2019, 2023) juga tahun dengan luas besar.",
"Takeaway  Nilai mentah tetap dipakai (tahun dasar 2025 menjadi acuan seluruh parameter dan kalibrasi); koreksi hanya alat diagnostik. Derau ini dibawa sebagai keterbatasan ke kalibrasi lahan.": "Takeaway  Nilai asli tetap dipakai (tahun dasar 2025 menjadi acuan seluruh parameter dan kalibrasi); koreksi hanya untuk pemeriksaan. Noise ini dicatat sebagai keterbatasan pada kalibrasi lahan.",
"Proksi tidak langsung; n = 7; selang prediksi lebar": "Ukuran tidak langsung (proxy); n = 7; selang prediksi lebar",
"Derau temporal (−27% 2023→2025); komisi dominan": "Noise antartahun (−27% 2023→2025); commission error dominan",
"Citra memperbarui variabel yang sudah punya data resmi; tidak menjadi variabel endogen dan tidak menggantikan statistik resmi. Statistik resmi tetap acuan utama.": "Citra hanya memperbarui variabel yang sudah punya data resmi; tidak dimasukkan sebagai variabel model dan tidak menggantikan statistik resmi. Statistik resmi tetap acuan utama.",
"Nilai citra kondisional: variabel yang dapat diklasifikasi langsung (lahan) lebih kuat daripada variabel yang memerlukan regresi proksi (ODTW).": "Manfaat citra bergantung pada jenis variabel: yang bisa diklasifikasi langsung (lahan) lebih kuat daripada yang perlu regresi proxy (ODTW).",
"Takeaway  Unsur \"memanfaatkan citra satelit untuk memutakhirkan variabel berjeda data\" pada Tujuan 2 terpenuhi, dengan kelayakan yang terukur.": "Takeaway  Bagian Tujuan 2 \"memanfaatkan citra satelit untuk memperbarui data yang terlambat tersedia\" terpenuhi, dengan kelayakan yang terukur.",
# --- Model
"Stock-flow diagram (SFD) pariwisata DIY · 26 variabel endogen, 35 eksogen": "Stock-flow diagram (SFD) pariwisata DIY · 26 variabel dihitung model, 35 input dari luar model",
"26 endogen + 35 eksogen = 61 variabel": "26 dihitung model + 35 input = 61 variabel",
"Dua tuas kebijakan": "Dua variabel kebijakan",
"Takeaway  SFD adalah operasionalisasi CLD menjadi model kuantitatif yang disimulasikan 2025–2050 (Δt 1 tahun, Euler). Persamaan lengkap di Lampiran 15.": "Takeaway  SFD adalah bentuk kuantitatif dari CLD dan disimulasikan 2025–2050 (Δt 1 tahun, metode Euler). Persamaan lengkap di Lampiran 15.",
"Laju Pertumbuhan Eksternal (turunan data)": "Laju Pertumbuhan Eksternal (dihitung dari data)",
"Laju Penurunan Dasar = 0,75 × LPE (rasio: asumsi struktural)": "Laju Penurunan Dasar = 0,75 × LPE (rasio 0,75: asumsi model)",
"Takeaway  Dua tuas menempel di dua jalur: Insentif Kebijakan pada investasi (R2), Kebijakan Konservasi Lahan pada konversi lahan pariwisata (B2). Pembatas MIN/MAX hasil perbaikan uji kondisi ekstrem.": "Takeaway  Dua variabel kebijakan bekerja di dua jalur: Insentif Kebijakan pada investasi (R2), Konservasi Lahan pada konversi lahan pariwisata (B2). Fungsi MIN/MAX ditambahkan setelah uji kondisi ekstrem.",
"• TPK ambang 0,275": "• Batas TPK pemicu konstruksi 0,275",
"Tidak (kecuali yang tidak pasti: ambang, konversi)": "Tidak (kecuali yang belum pasti: batas TPK, laju konversi)",
"Boleh (proksi)": "Boleh (nilai pendekatan)",
"Normalisasi & tuas": "Normalisasi & kebijakan",
"Konstruksi tersirat = ΔHotel + 0,05 × Hotel(t−1)": "Konstruksi (dihitung balik) = ΔHotel + 0,05 × Hotel(t−1)",
"Takeaway  LPE diperoleh dari koreksi Tahap 0 (sebelumnya 0,26864 karena mengasumsikan Daya Tarik 2024 = 1); rasio 0,75 adalah asumsi struktural yang diuji pada sensitivitas.": "Takeaway  LPE diperoleh dari koreksi Tahap 0 (sebelumnya 0,26864 karena menganggap Daya Tarik 2024 = 1); rasio 0,75 adalah asumsi model yang diuji pada analisis sensitivitas.",
"Asumsi struktural; data hanya mengidentifikasi selisih bersih LPE dan LPD": "Asumsi model; data hanya bisa menentukan selisih bersih LPE dan LPD",
"Sensitivitas ±10% (dinormalkan ulang) dan 2 kombinasi alternatif pada rentang penuh": "Sensitivitas ±10% (jumlah bobot dijaga = 1) dan 2 kombinasi alternatif",
"Triangulasi Permen PU 45/PRT/M/2007, UU 36/2008 Pasal 11(6), dan proksi laju penutupan ODTW": "Dibandingkan dari Permen PU 45/PRT/M/2007, UU 36/2008 Pasal 11(6), dan laju penutupan ODTW",
"Nilai tuas kebijakan": "Nilai variabel kebijakan",
"Ketetapan peneliti (tidak ada dokumen kebijakan yang memuat angka); dasar peraturan Perda 1/2012 dan 6/2021": "Ditentukan peneliti (tidak ada dokumen yang memuat angkanya); dasar peraturan Perda 1/2012 dan 6/2021",
"Kekokohan peringkat skenario pada 7 kondisi": "Robustness peringkat skenario pada 7 kondisi",
"Ambang indeks kepadatan": "Batas indeks kepadatan",
"Dibaca sebagai sinyal deskriptif, bukan pelanggaran standar": "Dibaca sebagai tanda peringatan, bukan standar resmi",
# --- Uji struktur
"Setiap hubungan kausal ditelusuri terhadap kriteria evaluasi CLD; setiap parameter harus jelas masuk salah satu kategori sumber (data resmi, identitas stok-aliran, regulasi, asumsi, normalisasi/tuas).": "Setiap hubungan kausal dicek dengan kriteria evaluasi CLD; setiap parameter harus jelas sumbernya (data resmi, persamaan stok-aliran, regulasi, asumsi, normalisasi/kebijakan).",
"Konsistensi dimensi": "Konsistensi satuan",
"Model boundary chart (Sterman, 2000): 26 variabel endogen, 35 eksogen, dan aspek yang dikeluarkan beserta konsekuensinya → menetapkan ranah tafsir hasil.": "Model boundary chart (Sterman, 2000): 26 variabel dihitung model, 35 input, dan aspek yang dikeluarkan beserta dampaknya → menentukan batas penafsiran hasil.",
"Kekekalan materi": "Keseimbangan stok",
"Stok tahun berikutnya dibandingkan dengan identitas Euler pada 5 stok, 2025–2049.": "Stok tahun berikutnya dicek dengan rumus stok + masuk − keluar pada 5 stok, 2025–2049.",
"Loop umpan balik (loop knockout)": "Feedback loop (loop knockout)",
"Satu loop dilumpuhkan per kali dengan menahan variabel penutupnya pada nilai tahun dasar (6 kasus: B1, B2, R2, okupansi, goal-seeking TK, semua rem).": "Satu loop dinonaktifkan setiap kali dengan menahan salah satu variabelnya pada nilai tahun dasar (6 kasus: B1, B2, R2, okupansi, goal-seeking TK, semua balancing loop).",
"Kriteria: arah perubahan sesuai polaritas loop": "Kriteria: arah perubahan sesuai jenis loop",
"Galat integrasi": "Error integrasi numerik",
"Uji loop umpan balik": "Uji feedback loop",
"Setiap loop penyeimbang yang dilumpuhkan justru mempercepat pertumbuhan": "Setiap balancing loop yang dinonaktifkan membuat pertumbuhan lebih cepat",
"Batas model: 61 variabel = 26 endogen + 35 eksogen. Guncangan eksternal, harga, promosi, musim, dan dampak lingkungan dikeluarkan.": "Batas model: 61 variabel = 26 dihitung model + 35 input. Shock eksternal, harga, promosi, musim, dan dampak lingkungan tidak dimasukkan.",
"Jumlah wisatawan 2050 (juta kunjungan) saat satu loop dilumpuhkan": "Jumlah wisatawan 2050 (juta kunjungan) saat satu loop dinonaktifkan",
"Tidak aditif": "Saling terkait",
"B1 saja dimatikan (250,3 juta) > semua rem dimatikan (217,4 juta), karena R2 tetap menguatkan daya tarik (1,0696)": "B1 saja dimatikan (250,3 juta) > semua balancing loop dimatikan (217,4 juta), karena R2 tetap menaikkan daya tarik (1,0696)",
"dari 17 uji: 15 lolos, 2 lolos dengan catatan (E02, E15); seluruh hipotesis perilaku terkonfirmasi": "dari 17 uji: 15 lolos, 2 lolos dengan catatan (E02, E15); semua perilaku sesuai dugaan awal",
"Uji galat integrasi (E15)": "Uji error integrasi (E15)",
"Lahan melewati luas wilayah 57,70 ha (0,018%) pada dt = 1; 0,01 ha pada dt 0,5; tidak melanggar pada dt 0,25 → galat numerik, bukan struktur.": "Lahan melewati luas wilayah 57,70 ha (0,018%) pada dt = 1; 0,01 ha pada dt 0,5; tidak melewati pada dt 0,25 → error perhitungan numerik, bukan kesalahan struktur.",
"Batas keberlakuan: LPE ≤ ±0,336 (≈1,25× nilai dasar). Simulasi dasar dt 1 vs 0,5 berselisih −0,27% s.d. +0,34% → langkah waktu tahunan memadai.": "Batas berlakunya model: LPE ≤ ±0,336 (≈1,25× nilai dasar). Simulasi dasar dt 1 vs 0,5 hanya berbeda −0,27% s.d. +0,34% → langkah waktu tahunan sudah cukup.",
# --- Uji perilaku
"Tanpa penggantian; seluruh umpan balik aktif; 9 variabel dinilai. Angka utama: dengan 2020–2021 (jendela hanya 7 tahun).": "Tanpa penggantian data; semua feedback aktif; 9 variabel dinilai. Angka utama: termasuk 2020–2021 (hanya 7 tahun data).",
"Penyambungan wisnus (untuk P5)": "Penyesuaian data wisnus (untuk P5)",
"α = 0,05 → sama · berbeda nyata · berlawanan arah. Bila berbeda, E1–E2 tidak ditafsirkan": "α = 0,05 → sama · berbeda nyata · berlawanan arah. Bila berbeda, E1–E2 tidak dibaca",
"2 · E1 galat rata-rata": "2 · E1 error rata-rata",
"3 · E2 galat variasi": "3 · E2 error variasi",
"Dekomposisi galat (Sterman, 1984)": "Dekomposisi error (Sterman, 1984)",
"Tanpa ambang: U1/U2 dominan → galat sistematis (dasar kalibrasi); U3 dominan → derau": "Tanpa batas nilai: U1/U2 dominan → error sistematis (perlu kalibrasi); U3 dominan → error acak",
"Patahan data wisnus 2018→2019 disambung dengan faktor 2,2997": "Data wisnus 2018→2019 disesuaikan dengan faktor 2,2997",
"lonjakan 2018→2019 (8,0 → 20,5 juta) akibat patahan metode pencacahan": "lonjakan 2018→2019 (8,0 → 20,5 juta) karena perubahan metode pencatatan",
"faktor penyambungan (rentang 2,22–2,38), diuji ulang pada kalibrasi diagnostik": "faktor penyesuaian (rentang 2,22–2,38), diuji ulang pada kalibrasi Tahap 3",
"Versi tanpa 2020–2021 (2016–2025). \"Sama\" = tren tidak berbeda nyata. E1/E2 P5 tidak ditafsirkan karena tren berbeda (Barlas, 1989). *DC P5 dari notebook repository (tidak ditabelkan di buku).": "Versi tanpa 2020–2021 (2016–2025). \"Sama\" = tren tidak berbeda nyata. E1/E2 P5 tidak dibaca karena trennya berbeda (Barlas, 1989). *DC P5 dari notebook repository (tidak ada di tabel buku).",
"Simulasi ±6,4%/th vs data sambungan ±11,7%/th; galat sistematis.": "Simulasi ±6,4%/th vs data ±11,7%/th; error sistematis.",
"Takeaway  Ketika masukan dari subsistem lain diganti data aktual, tiap subsistem mereproduksi pola historisnya (MAPE seluruhnya < 20%); masalah terlokalisasi pada subsistem wisatawan.": "Takeaway  Ketika input dari subsistem lain diganti data aktual, tiap subsistem bisa mengikuti pola datanya (MAPE seluruhnya < 20%); masalah hanya ada di subsistem wisatawan.",
"Kesesuaian pola (DC) lebih lemah daripada besaran galat (MAPE): galat menumpuk dari satu sumber bersama, bukan tersebar di banyak subsistem.": "Kesesuaian pola (DC) lebih lemah daripada besaran error (MAPE): error berasal dari satu sumber yang sama, bukan tersebar di banyak subsistem.",
"Error merambat dari susistem awal melalui jalur ekonomi": "Error terbawa dari subsistem wisatawan melalui jalur ekonomi",
"Komponen galat U1 (bias level) dominan pada 6 dari 9 variabel": "Komponen error U1 (bias rata-rata) dominan pada 6 dari 9 variabel",
"Kesenjangan tren berasal dari rezim pemulihan pascapandemi 2022–2024 yang berada di luar batas model (kenaikan wisnus nasional 2024: 21,61%) — bukan dari kekeliruan nilai parameter struktural subsistem wisatawan.": "Perbedaan tren berasal dari lonjakan pemulihan pascapandemi 2022–2024 yang tidak dicakup model (wisnus nasional 2024 naik 21,61%) — bukan dari nilai parameter subsistem wisatawan yang keliru.",
# --- Kalibrasi
"Hanya parameter tidak pasti (asumsi/estimasi). Data resmi, identitas stok-aliran, dan nilai referensi tidak dikalibrasi.": "Hanya parameter yang belum pasti (asumsi/estimasi). Data resmi, persamaan stok-aliran, dan nilai referensi tidak dikalibrasi.",
"Triangulasi rujukan, atau selang kepercayaan 95% tren log-linear:": "Dari beberapa rujukan, atau selang kepercayaan 95% tren log-linear:",
"Parameter berpasangan dihitung ulang": "Parameter yang saling terkait dihitung ulang",
"Pada setiap titik pencarian mengikuti identitas stok-aliran agar konsisten dengan data historis.": "Pada setiap nilai yang dicoba, dihitung ulang dengan persamaan stok-aliran agar tetap sesuai data historis.",
"NRMSE (sejalan dengan dekomposisi U1–U3); MAPE sebagai pelengkap.": "NRMSE (sejalan dengan dekomposisi U1–U3); MAPE sebagai pelengkap.",
"Himpunan indiferen": "Kumpulan nilai setara",
"Nilai turunan data ∈ I": "Nilai dari data ∈ I",
"Tidak teridentifikasi → nilai turunan dipertahankan": "Tidak bisa ditentukan → nilai dari data dipertahankan",
"Tahap 1 akomodasi: TPK ambang & laju demolisi (uji P1)": "Tahap 1 akomodasi: batas TPK & laju demolisi (uji P1)",
"Pemicu penolakan pada Tahap 4 (ambang 1,05)": "Syarat penolakan pada Tahap 4 (batas 1,05)",
"S uji kondisi ekstrem gagal / aturan fisik dilanggar": "S uji kondisi ekstrem gagal / aturan fisik dilanggar",
"TPK ambang dan laju demolisi dicari menyeluruh. Optimum TPK (0,35) di batas rentang dan gagal generalisasi lintas periode": "Batas TPK dan laju demolisi dicari menyeluruh. Optimum TPK (0,35) ada di ujung rentang dan berubah bila periode data diganti",
"LPE dan LPD tidak teridentifikasi terpisah; data hanya mengidentifikasi selisih bersihnya → diagnostik saja": "LPE dan LPD tidak bisa ditentukan terpisah; data hanya menentukan selisih bersihnya → hanya untuk pemeriksaan",
"3 parameter diuji (TPK ambang, laju demolisi, laju konversi) → 0 berubah": "3 parameter diuji (batas TPK, laju demolisi, laju konversi) → 0 berubah",
"Nilai turunan data sudah berada di daerah yang dapat dipertanggungjawabkan: kalibrasi berfungsi sebagai instrumen validasi, bukan penyesuaian (Oliva, 2003).": "Nilai yang dihitung dari data sudah dapat dipertanggungjawabkan: kalibrasi berfungsi sebagai alat validasi, bukan untuk mengubah nilai (Oliva, 2003).",
"Punggung keteridentifikasian: LPE 0,26–0,80 berpasangan dengan rasio 0,60–0,86": "Banyak pasangan nilai sama baiknya: LPE 0,26–0,80 dengan rasio 0,60–0,86",
"Takeaway  Data hanya mengidentifikasi selisih bersih LPE dan LPD; lonjakan 2022–2024 (puncak 24,86%) adalah rezim di luar batas model (wisnus nasional 2024 +21,61%). LPE/LPD dipertahankan.": "Takeaway  Data hanya bisa menentukan selisih bersih LPE dan LPD; lonjakan 2022–2024 (puncak 24,86%) adalah pemulihan pascapandemi yang tidak dicakup model (wisnus nasional 2024 +21,61%). LPE/LPD dipertahankan.",
"Struktur  6 uji struktur lolos: satuan konsisten, materi kekal, 6/6 loop berfungsi, 17 uji ekstrem 0 gagal, langkah waktu memadai.": "Struktur  6 uji struktur lolos: satuan konsisten, stok seimbang, 6/6 loop berfungsi, 17 uji ekstrem 0 gagal, langkah waktu cukup.",
"MEMADAI": "CUKUP BAIK",
"Perilaku model penuh  Tidak ada variabel berkategori MAPE buruk; DC melemah karena galat merambat dari satu sumber.": "Perilaku model penuh  Tidak ada variabel dengan MAPE buruk; DC melemah karena error terbawa dari satu sumber.",
"MEMADAI, DENGAN CATATAN": "CUKUP BAIK, DENGAN CATATAN",
"Sumber galat  Terlokalisasi pada pertumbuhan wisatawan → rezim pemulihan pascapandemi di luar batas model, bukan kesalahan parameter.": "Sumber error  Hanya pada pertumbuhan wisatawan → lonjakan pemulihan pascapandemi yang tidak dicakup model, bukan kesalahan parameter.",
"Nilai parameter  Kalibrasi 3 parameter → 0 berubah; nilai turunan data terkonfirmasi (Oliva, 2003).": "Nilai parameter  Kalibrasi 3 parameter → 0 berubah; nilai dari data terkonfirmasi (Oliva, 2003).",
"Tanpa guncangan eksternal": "Tanpa shock eksternal",
"Rasio LPD/LPE tidak teridentifikasi": "Rasio LPD/LPE tidak bisa ditentukan dari data",
# --- Sensitivitas & skenario
"Prosedur Mai dan Smith (2018): 32 parameter diubah naik dan turun 10%, satu parameter per simulasi. Kedua tuas dikecualikan (bernilai nol pada kondisi dasar).": "Prosedur Mai dan Smith (2018): 32 parameter dinaikkan dan diturunkan 10%, satu parameter per simulasi. Kedua variabel kebijakan tidak diuji di sini (nilainya nol pada kondisi dasar).",
"Bagian 2 · Rentang penuh": "Bagian 2 · Seluruh rentang nilai",
"17 kelompok parameter berstatus asumsi beserta kedua tuas diuji pada seluruh rentangnya (triangulasi rujukan atau selang kepercayaan 95%, sama dengan rentang kalibrasi).": "17 kelompok parameter asumsi dan kedua variabel kebijakan diuji pada seluruh rentang nilainya (dari beberapa rujukan atau selang kepercayaan 95%, sama dengan rentang kalibrasi).",
"Lebar rentang = Keluaran_maks − Keluaran_min": "Selisih hasil = Keluaran_maks − Keluaran_min",
"Kekokohan peringkat skenario": "Robustness peringkat skenario",
"Kokoh bila urutan skenario pada 7 indikator identik di C0–C6": "Robust bila urutan skenario pada 7 indikator sama di C0–C6",
"Parameter berpasangan dihitung ulang (LPE–LPD rasio 0,75; TPK ambang/demolisi–sensitivitas konstruksi; penutupan ODTW–sensitivitas ODTW; luas lahan–nilai referensi); ketiga bobot daya tarik dinormalisasi ulang agar berjumlah 1; nilai awal stok diubah melalui kondisi awal simulasi.": "Parameter yang saling terkait dihitung ulang (LPE–LPD rasio 0,75; batas TPK/demolisi–sensitivitas konstruksi; penutupan ODTW–sensitivitas ODTW; luas lahan–nilai referensi); ketiga bobot daya tarik dijaga berjumlah 1; nilai awal stok diubah melalui kondisi awal simulasi.",
"Penetapan tuas kebijakan": "Penetapan variabel kebijakan",
"Hasil sensitivitas menjadi kriteria pertama (relevansi struktural), lalu disaring dengan dasar kebijakan dan keterkendalian → Insentif Kebijakan dan Kebijakan Konservasi Lahan.": "Hasil sensitivitas menjadi kriteria pertama (berpengaruh pada model), lalu disaring dengan dasar kebijakan dan kewenangan pemerintah → Insentif Kebijakan dan Kebijakan Konservasi Lahan.",
"Turunan data": "Dihitung dari data",
"peringkat teratas berstatus asumsi (laju penurunan dasar, bobot kepadatan, bobot ODTW)": "peringkat teratas adalah asumsi (laju penurunan dasar, bobot kepadatan, bobot ODTW)",
"lebar rentang wisatawan akibat rasio LPD/LPE 0,60–0,90 (LPE tetap); 69,65 bila LPE diturunkan ulang": "selisih hasil wisatawan akibat rasio LPD/LPE 0,60–0,90 (LPE tetap); 69,65 bila LPE dihitung ulang",
"Relevansi struktural": "Berpengaruh pada model",
"Keterkendalian": "Dapat dikendalikan pemerintah",
"Lolos ketiganya → dua tuas kebijakan": "Memenuhi ketiganya → dua variabel kebijakan",
"Tidak menjadi tuas": "Tidak dijadikan variabel kebijakan",
"Parameter yang hanya relevan struktural (perilaku wisatawan, bobot indeks) diuji sebagai ketidakpastian. Pembangunan ODTW jalur pemerintah: data pemisahan sumber pembiayaan tidak tersedia.": "Parameter yang berpengaruh tetapi tidak bisa dikendalikan pemerintah (perilaku wisatawan, bobot indeks) diuji sebagai ketidakpastian. Pembangunan ODTW oleh pemerintah: data sumber pembiayaannya tidak tersedia.",
"Skenario berupa paket dua tuas → atribusi dilakukan lewat simulasi dekomposisi (analisis pendukung, bukan skenario).": "Skenario adalah paket dua variabel kebijakan → kontribusi masing-masing dipisahkan lewat simulasi tambahan (bukan skenario baru).",
"Investasi kumulatif (miliar Rp) · deskriptif": "Investasi kumulatif (miliar Rp) · gambaran",
"Rasio daya dukung lahan (ambang > 0,331)": "Rasio daya dukung lahan (batas > 0,331)",
"Indeks kepadatan (ambang < 2,0)": "Indeks kepadatan (batas < 2,0)",
"Lintasan 2025–2050: jumlah wisatawan (kiri) dan PDRB sektor pariwisata (kanan) menurut skenario": "Perkembangan 2025–2050: jumlah wisatawan (kiri) dan PDRB sektor pariwisata (kanan) menurut skenario",
"RDDL ≈ 0,614, jauh di atas ambang 0,331 → hingga 2050 rem daya dukung lahan belum bekerja berarti; pertumbuhan atraksi lebih menentukan daya tarik daripada tekanan lahan.": "RDDL ≈ 0,614, jauh di atas batas 0,331 → sampai 2050 daya dukung lahan belum menahan pertumbuhan; pertambahan atraksi lebih menentukan daya tarik daripada tekanan lahan.",
"Indeks kepadatan menurut skenario, 2025–2050, dengan garis ambang 2,0": "Indeks kepadatan menurut skenario, 2025–2050, dengan garis batas 2,0",
"tahun ambang 2,0 terlampaui — selisih antarskenario hanya 2 tahun": "tahun batas 2,0 terlewati — selisih antarskenario hanya 2 tahun",
"Kedua tuas bekerja di sisi penyediaan (investasi, lahan); kepadatan ditentukan pertumbuhan permintaan.": "Kedua variabel kebijakan bekerja di sisi penyediaan (investasi, lahan), sedangkan kepadatan ditentukan pertumbuhan jumlah wisatawan.",
"Rasio daya dukung lahan ≈ 0,614 — ambang 0,331 tidak terlampaui": "Rasio daya dukung lahan ≈ 0,614 — batas 0,331 tidak terlewati",
"Ambang 2,0 = ketetapan peneliti (2× kepadatan tahun dasar): sinyal deskriptif": "Batas 2,0 ditentukan peneliti (2× kepadatan tahun dasar): tanda peringatan, bukan standar resmi",
"Kontribusi tuas = keluaran tuas tunggal − tanpa intervensi · Efek interaksi = selisih paket − (kontribusi insentif + konservasi)": "Kontribusi = hasil satu kebijakan saja − tanpa kebijakan · Efek interaksi = selisih paket − (kontribusi insentif + konservasi)",
"Interaksi hanya ≈ 0,7% dari selisih paket pada jumlah wisatawan: kontribusi kedua tuas hampir bersifat aditif.": "Interaksi hanya ≈ 0,7% dari selisih paket pada jumlah wisatawan: efek kedua kebijakan hampir bisa langsung dijumlahkan.",
"Interaksi −57,6 ha menetralkan +57,6 ha dari insentif: Sustainable menihilkan konversi lahan pariwisata tanpa kehilangan pertumbuhan ekonomi → portofolio kebijakan dapat dirancang modular.": "Interaksi −57,6 ha menghapus tambahan +57,6 ha dari insentif: Sustainable membuat konversi lahan pariwisata menjadi nol tanpa mengurangi pertumbuhan ekonomi → kedua kebijakan dapat dirancang terpisah.",
"KOKOH": "ROBUST",
"Kokoh pada peringkat, bukan pada besaran: angka absolut 2050 berubah cukup besar antarkondisi → hasil bukan ramalan.": "Yang robust adalah urutannya, bukan besarannya: angka 2050 berubah cukup besar antarkondisi → hasil bukan ramalan.",
"Development Priority tertinggi pada lapangan kerja dan nilai tambah, dengan konversi lahan pariwisata +15,64% vs BAU dan kepadatan tertinggi. Sustainable menihilkan konversi lahan fasilitas pariwisata sambil tetap tumbuh lebih tinggi dari BAU.": "Development Priority tertinggi pada lapangan kerja dan nilai tambah, tetapi konversi lahan pariwisata +15,64% vs BAU dan kepadatan tertinggi. Sustainable membuat konversi lahan fasilitas pariwisata menjadi nol dan tetap tumbuh lebih tinggi dari BAU.",
"Ambang kepadatan terlampaui 2041–2043 pada ketiga skenario; diperlukan pengelolaan sebaran kunjungan antarwaktu dan antarlokasi, di luar cakupan model.": "Batas kepadatan terlewati pada 2041–2043 di ketiga skenario; perlu pengaturan sebaran kunjungan antarwaktu dan antarlokasi, di luar cakupan model.",
"Perda DIY 1/2012 (pembukaan lahan baru) vs Perda DIY 6/2021 (larangan alih fungsi lahan pangan) terpotret secara kuantitatif dalam Development Priority vs Sustainable.": "Perbedaan arah Perda DIY 1/2012 (pembukaan lahan baru) dan Perda DIY 6/2021 (larangan alih fungsi lahan pangan) terlihat dalam angka Development Priority vs Sustainable.",
"6 uji struktur lolos (17 uji ekstrem tanpa gagal); perilaku memadai per subsistem; kalibrasi tidak mengubah parameter.": "6 uji struktur lolos (17 uji ekstrem tanpa gagal); perilaku cukup baik per subsistem; kalibrasi tidak mengubah parameter.",
"Tidak ada skenario unggul di ketiga dimensi; DP unggul ekonomi, Sustainable unggul lingkungan, BAU unggul kepadatan — urutan kokoh pada 7 kondisi.": "Tidak ada skenario unggul di ketiga dimensi; DP unggul ekonomi, Sustainable unggul lingkungan, BAU unggul kepadatan — urutannya robust pada 7 kondisi.",
"Takeaway  Model terintegrasi citra, tervalidasi, dan mampu membandingkan skenario kebijakan secara kuantitatif beserta kekokohannya.": "Takeaway  Model memanfaatkan citra, sudah divalidasi, dan mampu membandingkan skenario kebijakan secara kuantitatif beserta tingkat robustness-nya.",
# --- Tujuan 3
"Halaman Simulasi: atur 2 tuas, pilih variabel": "Halaman Simulasi: atur 2 variabel kebijakan, pilih variabel",
"atur dua tuas, pilih variabel, jalankan 2025–2050": "atur dua variabel kebijakan, pilih variabel, jalankan 2025–2050",
"Takeaway  Fungsi utama berjalan sesuai spesifikasi (100% kasus uji). Pengujian terbatas pada kasus yang ditetapkan dan tidak menilai kemudahan penggunaan — itu dinilai lewat SUS.": "Takeaway  Fungsi utama berjalan sesuai rancangan (100% kasus uji). Pengujian ini tidak menilai kemudahan penggunaan — itu dinilai lewat SUS.",
"Masukan: 2 responden sulit menafsirkan grafik/hasil simulasi, 1 responden bingung pada tampilan dua garis tuas. Saran: interpretasi otomatis, panduan penggunaan, chatbot.": "Masukan: 2 responden sulit membaca grafik/hasil simulasi, 1 responden bingung pada tampilan dua garis pengatur kebijakan. Saran: penjelasan hasil otomatis, panduan penggunaan, chatbot.",
"Beranda, Model (struktur & evaluasi), Skenario (tiga skenario + perbandingan), Simulasi (dua tuas, pilihan variabel, 2025–2050).": "Beranda, Model (struktur & evaluasi), Skenario (tiga skenario + perbandingan), Simulasi (dua variabel kebijakan, pilihan variabel, 2025–2050).",
# --- Penutup
"Tiga parameter diuji (TPK ambang, laju demolisi, laju konversi) dan tidak satu pun berubah. Nilai turunan data dan identitas stok-aliran sudah berada di daerah yang dapat dipertanggungjawabkan — sejalan dengan Oliva (2003): kalibrasi sebagai pengujian hipotesis struktural.": "Tiga parameter diuji (batas TPK, laju demolisi, laju konversi) dan tidak satu pun berubah. Nilai yang dihitung dari data sudah dapat dipertanggungjawabkan — sejalan dengan Oliva (2003): kalibrasi dipakai untuk menguji struktur model.",
"Nilai citra satelit bersifat kondisional": "Manfaat citra satelit bergantung pada jenis variabel",
"Lahan terbangun: Dynamic World diklasifikasi langsung, tanpa model regresi tambahan. ODTW: cahaya malam memerlukan regresi proksi dengan kekuatan moderat (R² selisih tahunan 0,405). Manfaat citra bergantung pada apakah variabel dapat diklasifikasi langsung atau butuh hubungan statistik.": "Lahan terbangun: Dynamic World diklasifikasi langsung, tanpa regresi tambahan. ODTW: cahaya malam memerlukan regresi proxy dengan kekuatan sedang (R² selisih tahunan 0,405). Manfaat citra bergantung pada apakah variabel bisa diklasifikasi langsung atau butuh hubungan statistik.",
"Dua tuas dapat dirancang modular": "Dua kebijakan dapat dirancang terpisah",
"Efek interaksi hanya ≈ 0,7% dari selisih paket pada jumlah wisatawan: insentif menggerakkan ekonomi, konservasi menggerakkan lahan. Satu tuas dapat ditambah atau dikurangi tanpa mengulang seluruh simulasi untuk memperkirakan dampaknya.": "Efek interaksi hanya ≈ 0,7% dari selisih paket pada jumlah wisatawan: insentif menggerakkan ekonomi, konservasi menggerakkan lahan. Satu kebijakan dapat ditambah atau dikurangi tanpa mengulang seluruh simulasi untuk memperkirakan dampaknya.",
"Kontribusi penelitian: kerangka pengujian yang membedakan sumber ketidaksesuaian, serta pemetaan pertukaran kebijakan secara kuantitatif beserta kekokohannya terhadap ketidakpastian struktural.": "Kontribusi penelitian: cara pengujian yang bisa memisahkan sumber ketidaksesuaian, serta gambaran trade-off kebijakan secara kuantitatif beserta robustness-nya terhadap ketidakpastian asumsi.",
"Patahan metode wisnus 2018/2019 (faktor sambung 2,22–2,38)": "Perubahan metode pencatatan wisnus 2018/2019 (faktor penyesuaian 2,22–2,38)",
"Lahan terbangun berderau (−27% dalam dua tahun)": "Data lahan terbangun mengandung noise (−27% dalam dua tahun)",
"Tanpa guncangan, harga, promosi, musim, dan lingkungan": "Tanpa shock, harga, promosi, musim, dan lingkungan",
"Rasio LPD/LPE: asumsi, tidak teridentifikasi dari data": "Rasio LPD/LPE: asumsi, tidak bisa ditentukan dari data",
"Nilai tuas dan ambang kepadatan 2,0: ketetapan peneliti": "Nilai variabel kebijakan dan batas kepadatan 2,0: ditentukan peneliti",
"Teridentifikasi dan dirumuskan: 5 stock, 10 flow, 11 auxiliary, 35 parameter, dengan enam loop umpan balik — teradaptasi dari Mai & Smith (2018) ke ketersediaan data resmi Indonesia.": "Teridentifikasi dan dirumuskan: 5 stock, 10 flow, 11 auxiliary, 35 parameter, dengan enam feedback loop — diadaptasi dari Mai & Smith (2018) sesuai ketersediaan data resmi Indonesia.",
"Valid secara struktural dan memadai pada tingkat subsistem; kalibrasi tidak mengubah parameter apa pun. Tiga skenario: tidak ada yang unggul di semua dimensi, dan pola ini kokoh terhadap ketidakpastian parameter terbesar.": "Struktur model valid dan perilakunya cukup baik per subsistem; kalibrasi tidak mengubah parameter apa pun. Tiga skenario: tidak ada yang unggul di semua dimensi, dan pola ini robust terhadap ketidakpastian parameter terbesar.",
"Model tervalidasi mampu membandingkan skenario kebijakan secara kuantitatif beserta tingkat kekokohannya.": "Model yang sudah divalidasi mampu membandingkan skenario kebijakan secara kuantitatif beserta tingkat robustness-nya.",
"Perkuat dasar empiris parameter berstatus ketetapan, terutama rasio laju penurunan/pertumbuhan wisatawan dan ambang kepadatan, melalui survei primer (niat berkunjung kembali, daya dukung sosial) di destinasi utama DIY.": "Perkuat dasar data untuk parameter yang ditentukan peneliti, terutama rasio laju penurunan/pertumbuhan wisatawan dan batas kepadatan, melalui survei primer (niat berkunjung kembali, daya dukung sosial) di destinasi utama DIY.",
"Tambahkan mekanisme guncangan eksternal (mis. pandemi); pisahkan data pembangunan ODTW menurut sumber pembiayaan bersama Dinas Pariwisata dan Bappeda DIY; verifikasi silang Dynamic World pada tahun berderau tertinggi.": "Tambahkan shock eksternal (mis. pandemi); pisahkan data pembangunan ODTW menurut sumber pembiayaan bersama Dinas Pariwisata dan Bappeda DIY; cek ulang Dynamic World pada tahun dengan noise tertinggi.",
"Libatkan lokakarya pemangku kepentingan agar nilai tuas kebijakan mencerminkan kesepakatan pihak yang berwenang menerapkannya.": "Libatkan lokakarya pemangku kepentingan agar nilai variabel kebijakan sesuai kesepakatan pihak yang berwenang menerapkannya.",
"Kalibrasi menjadi instrumen validasi": "Kalibrasi sebagai alat validasi",
# --- Lampiran
"TPK ambang: 0,275": "Batas TPK: 0,275",
"RMSE relatif LOOCV 5,99% (galat terbesar: 2022 −8,2%, 2023 +7,0%, 2024 −8,9%)": "RMSE relatif LOOCV 5,99% (error terbesar: 2022 −8,2%, 2023 +7,0%, 2024 −8,9%)",
"Komisi dominan: 34 titik peta terbangun yang rujukannya bukan terbangun, dibanding 5 omisi.": "Commission error dominan: 34 titik terpetakan terbangun padahal bukan, dibanding 5 omission error.",
"Kesalahan terkonsentrasi pada titik berprobabilitas dekat ambang 0,5 (akurasi 52,0% pada selang 0,5–0,6 vs 97,7% pada 0–0,25): piksel campuran di tepi objek, bukan kesalahan acak.": "Kesalahan terkumpul pada titik dengan probabilitas dekat 0,5 (akurasi 52,0% pada selang 0,5–0,6 vs 97,7% pada 0–0,25): piksel campuran di tepi objek, bukan kesalahan acak.",
"• TK 2015–2016: NTL (R² selisih 0,070) dan PDRB (R² selisih 0,093) ditolak sebagai estimator; dipakai CAGR 2017–2025.": "• TK 2015–2016: NTL (R² selisih 0,070) dan PDRB (R² selisih 0,093) tidak layak sebagai penduga; dipakai CAGR 2017–2025.",
"Dynamic World: GOOGLE/DYNAMICWORLD/V1, band built dirata-ratakan per tahun, ambang ≥ 0,5, pixelArea, skala 10 m.": "Dynamic World: GOOGLE/DYNAMICWORLD/V1, band built dirata-ratakan per tahun, batas probabilitas ≥ 0,5, pixelArea, skala 10 m.",
"Ambang": "Batas",
"Deskriptif": "Gambaran",
"Tingkat penghunian kamar (deskriptif)": "Tingkat penghunian kamar (gambaran)",
"Tahun ambang kepadatan 2,0 terlampaui": "Tahun batas kepadatan 2,0 terlewati",
"TPK tercantum sebagai KPI deskriptif pada Tabel 21 buku tetapi tidak muncul di Tabel 60; nilainya diambil dari hasil_simulasi_skenario.xlsx (23 run: 3 skenario × 7 kondisi + 2 dekomposisi).": "TPK tercantum sebagai KPI gambaran pada Tabel 21 buku tetapi tidak ada di Tabel 60; nilainya diambil dari hasil_simulasi_skenario.xlsx (23 run: 3 skenario × 7 kondisi + 2 simulasi kontribusi).",
"Pedoman: E1 < 0,05 · E2 < 0,30 · DC 0,4–0,7 = rata-rata sampai baik · MAPE <10% sangat baik, 10–20% baik, 20–50% layak, >50% buruk. E1/E2 wisatawan (uji penuh) tidak ditafsirkan karena tren berbeda nyata.": "Pedoman: E1 < 0,05 · E2 < 0,30 · DC 0,4–0,7 = rata-rata sampai baik · MAPE <10% sangat baik, 10–20% baik, 20–50% layak, >50% buruk. E1/E2 wisatawan (uji penuh) tidak dibaca karena trennya berbeda nyata.",
"Penyeimbang lewat harga tidak tercakup": "Pengaruh harga tidak tercakup",
"Tersirat dalam laju pertumbuhan eksternal": "Sudah termasuk dalam laju pertumbuhan eksternal",
"Guncangan: pandemi, erupsi, gempa": "Shock: pandemi, erupsi, gempa",
"Peristiwa acak di luar struktur umpan balik": "Kejadian acak di luar struktur feedback",
"Lintasan tanpa guncangan": "Proyeksi tanpa shock",
"Masuk jalur non-investasi yang eksogen": "Masuk sebagai input tetap (non-investasi)",
"TPK ambang = 1": "Batas TPK = 1",
"Lampiran 11 · Uji loop umpan balik: nilai 2050 saat satu loop dilumpuhkan": "Lampiran 11 · Uji feedback loop: nilai 2050 saat satu loop dinonaktifkan",
"Seluruh rem dimatikan (R1 murni)": "Semua balancing loop dimatikan (hanya R1)",
"• B1 paling kuat dan sistemik: wisatawan 2050 +160,2%, 5 dari 6 variabel berubah >1%": "• B1 paling kuat dan berpengaruh luas: wisatawan 2050 +160,2%, 5 dari 6 variabel berubah >1%",
"• Tidak aditif: B1 saja (250,32 juta) > seluruh rem dimatikan (217,37 juta) karena R2 tetap menguatkan daya tarik": "• Efeknya tidak bisa dijumlahkan: B1 saja (250,32 juta) > semua balancing loop dimatikan (217,37 juta) karena R2 tetap menaikkan daya tarik",
"Wisatawan memuncak ±122,9 juta pada 2080 lalu turun ketika RDDL mendekati nol: pola overshoot–penurunan khas struktur daya dukung (limits to growth). Simulasi tetap stabil (TPK maks 0,388; daya tarik min 0,715). Uji ini dirujuk di Buku 4.3.2.4 sebagai dasar pemilihan bobot dan elastisitas; tabelnya hanya ada di repository.": "Wisatawan mencapai puncak ±122,9 juta pada 2080 lalu turun ketika RDDL mendekati nol: pola overshoot lalu turun, khas model daya dukung (limits to growth). Simulasi tetap stabil (TPK maks 0,388; daya tarik min 0,715). Uji ini dirujuk di Buku 4.3.2.4 sebagai dasar pemilihan bobot dan elastisitas; tabelnya hanya ada di repository.",
"Optimum TPK ambang 0,35 tepat di batas rentang; perbaikan 11,64% bertumpu pada tahun 2019 dan gagal generalisasi (P1b, versi COVID). Dipertahankan: 0,275 dan 0,05.": "Optimum batas TPK 0,35 tepat di ujung rentang; perbaikan 11,64% hanya karena tahun 2019 dan tidak konsisten pada versi dengan COVID maupun rancangan P1b. Dipertahankan: 0,275 dan 0,05.",
"Punggung himpunan indiferen: LPE dan rasio LPD/LPE tidak teridentifikasi terpisah; data hanya mengidentifikasi selisih bersih. Dipertahankan.": "Banyak pasangan nilai sama baiknya: LPE dan rasio LPD/LPE tidak bisa ditentukan terpisah; data hanya menentukan selisih bersihnya. Dipertahankan.",
"Parameter (rentang penuh)": "Parameter (seluruh rentang)",
"Rasio LPD/LPE (LPE diturunkan ulang)": "Rasio LPD/LPE (LPE dihitung ulang)",
"Lebar rentang dalam poin persen": "Selisih hasil tertinggi–terendah (poin persen)",
}
