# slide (nomor di file user) -> (judul, resume)
TITLES = {
3: ('Latar Belakang', 'Pariwisata adalah sektor strategis yang terus tumbuh'),
4: ('Latar Belakang', 'Peran pariwisata di Indonesia terus menguat'),
5: ('Latar Belakang', 'DIY adalah destinasi utama dan didukung kebijakan yang kuat'),
6: ('Latar Belakang — Permasalahan', 'Pertumbuhan yang pesat menekan daya dukung destinasi'),
7: ('Latar Belakang — Pendekatan Sistem Dinamis', 'Metode peramalan biasa kurang tepat untuk perencanaan jangka panjang'),
8: ('Identifikasi Masalah dan Tujuan Penelitian', 'Tiga permasalahan dijawab oleh tiga tujuan penelitian'),
9: ('Batasan Masalah', 'Model dipakai untuk membandingkan skenario, bukan untuk meramal angka'),
10: ('Kontribusi Penelitian Terkait', 'Dibanding 9 studi sebelumnya, penelitian ini menggabungkan tiga unsur sekaligus'),
11: ('Kerangka Pikir Penelitian', 'Alur dari permasalahan sampai keluaran penelitian'),
12: ('Lokasi Penelitian, Data, dan Sumber Data', 'Data resmi 2015–2025 menjadi dasar model'),
13: ('Tahapan Penelitian', 'Enam tahap penelitian untuk menjawab tiga tujuan'),
14: ('Alat dan Perangkat Lunak', 'Perangkat yang digunakan pada setiap tahap'),
15: ('Pengumpulan dan Preprocessing Data', 'Empat masalah data ditangani sebelum pemodelan'),
17: ('Identifikasi dan Perumusan Variabel CLD', 'Variabel disusun dari model rujukan, disesuaikan dengan kondisi DIY, lalu dievaluasi'),
18: ('Hasil Identifikasi dan Evaluasi Variabel CLD', 'CLD disusun melalui adaptasi dan evaluasi, bukan menyalin model rujukan'),
19: ('Perumusan dan Evaluasi Hubungan Kausal', '18 hubungan sebab-akibat beserta dasar masing-masing'),
20: ('Causal Loop Diagram dan Feedback Loop', 'CLD akhir memiliki dua reinforcing loop dan empat balancing loop'),
21: ('Penetapan Batas Model', 'Batas model menentukan sejauh mana hasil boleh ditafsirkan'),
24: ('Integrasi Data Citra Satelit', 'Citra satelit dipakai untuk memperbarui data, bukan menggantikan statistik resmi'),
25: ('Estimasi Jumlah ODTW dengan Night-Time Light', 'Tahapan estimasi ODTW: dari citra VIIRS sampai regresi dan selang prediksi'),
26: ('Validasi dan Evaluasi Kelayakan Data Citra', 'Ukuran yang dipakai untuk menilai kelayakan NTL dan Dynamic World'),
27: ('Estimasi Jumlah ODTW', 'Cahaya malam (NTL) layak dipakai untuk mengestimasi jumlah ODTW'),
28: ('Estimasi ODTW — Validasi Temporal dan Spasial', 'NTL mengisi data ODTW 2015–2017 dan 2025, dan konsisten secara spasial'),
29: ('Estimasi Lahan Terbangun — Uji Akurasi', 'Dynamic World akurat, tetapi data tahunannya mengandung noise'),
30: ('Diagnosis Ketidakstabilan Temporal', 'Naik-turunnya data Dynamic World disebabkan jumlah observasi, bukan perubahan lahan'),
31: ('Simpulan Integrasi Data Citra Satelit', 'Dua variabel berhasil diperbarui; kekuatannya bergantung pada jenis variabel'),
32: ('Konversi ke Stock-Flow Diagram', 'Model akhir memuat 61 variabel dengan lima stok utama'),
33: ('Stock-Flow Diagram', 'Stock-flow diagram pariwisata DIY'),
34: ('Persamaan Stok — Subsistem Wisatawan', 'Daya Tarik Destinasi menghubungkan seluruh loop utama'),
35: ('Persamaan Stok — Subsistem Lainnya', 'Persamaan akomodasi, ODTW, tenaga kerja, lahan, dan letak variabel kebijakan'),
36: ('Penetapan Parameter', '35 parameter dari lima jenis sumber; hanya yang belum pasti boleh dikalibrasi'),
37: ('Penurunan Nilai Parameter', 'Contoh perhitungan parameter: berasal dari data, bukan ditebak'),
38: ('Parameter Asumsi Pemodelan', 'Asumsi peneliti disampaikan terbuka beserta dasar dan cara mengujinya'),
39: ('Rancangan Uji Struktur', 'Struktur model diperiksa dulu sebelum dibandingkan dengan data'),
40: ('Konsistensi Satuan, Batas Model, dan Keseimbangan Stok', 'Struktur model lolos seluruh uji verifikasi'),
41: ('Uji Feedback Loop', 'Loop kepadatan (B1) adalah balancing loop yang paling kuat'),
42: ('Uji Kondisi Ekstrem dan Error Integrasi', 'Pada kondisi ekstrem, fungsi pembatas dalam model bekerja dengan benar'),
43: ('Rancangan Uji Perilaku', 'Pola hasil simulasi dibandingkan dengan data, mengikuti urutan Barlas'),
44: ('Rancangan Uji Perilaku — Penyesuaian Data Wisnus', 'Perubahan metode pencatatan wisnus 2018→2019 disesuaikan dengan faktor 2,2997'),
45: ('Hasil Uji Parsial', 'Tiap subsistem cukup baik; hanya subsistem wisatawan yang gagal uji tren'),
46: ('Hasil Uji Penuh', 'Hasil per subsistem baik, tetapi melemah saat seluruh subsistem dijalankan bersama'),
47: ('Hasil Uji Penuh — Sumber Error', 'Error berasal dari satu sumber: pertumbuhan wisatawan, lalu terbawa ke variabel lain'),
48: ('Protokol Kalibrasi', 'Aturan kalibrasi ditetapkan sebelum pencarian nilai dilakukan'),
49: ('Hasil Kalibrasi Tahap 0–4', 'Kalibrasi menguatkan nilai parameter dari data — tidak ada yang diganti'),
50: ('Kalibrasi Diagnostik Subsistem Wisatawan', 'Selisih pertumbuhan wisatawan berasal dari lonjakan pemulihan pascapandemi'),
51: ('Rangkuman Kelayakan Model', 'Apakah model layak untuk simulasi skenario? Bukti dan batasnya'),
52: ('Rancangan Analisis Sensitivitas', 'Sensitivitas diuji dari perubahan ±10% sampai seluruh rentang nilai'),
53: ('Hasil Analisis Sensitivitas', 'Ketidakpastian terbesar ada pada asumsi, bukan pada data'),
54: ('Kriteria Penetapan Variabel Kebijakan', 'Variabel kebijakan dipilih dengan tiga kriteria sekaligus'),
55: ('Rancangan Skenario dan Indikator Kinerja', 'Tiga skenario dari kombinasi dua variabel kebijakan'),
56: ('Hasil Perbandingan Skenario', 'Tidak ada skenario yang unggul di ketiga dimensi sekaligus'),
57: ('Hasil Perbandingan Skenario — Komposisi Daya Tarik', 'Pertambahan ODTW lebih berpengaruh daripada tekanan kepadatan dan lahan'),
58: ('Hasil Perbandingan Skenario — Batas Kepadatan', 'Kedua variabel kebijakan hanya menunda waktu terlewatinya batas kepadatan'),
59: ('Kontribusi Masing-masing Variabel Kebijakan', 'Kedua variabel kebijakan bekerja di jalur berbeda, sehingga efeknya hampir tidak saling memengaruhi'),
60: ('Robustness Peringkat Skenario', 'Urutan skenario tetap sama pada tujuh kondisi parameter'),
61: ('Implikasi Kebijakan', 'Simulasi menunjukkan trade-off antarpilihan kebijakan, bukan satu jawaban tunggal'),
64: ('Implementasi Aplikasi Berbasis Web', 'Alasan pembuatan aplikasi dan kebutuhan pengguna'),
65: ('Arsitektur dan Implementasi Aplikasi', 'Model dapat dicoba langsung tanpa software pemodelan'),
66: ('Implementasi Aplikasi — Halaman Aplikasi', 'Empat halaman aplikasi: dari input kebijakan sampai grafik hasil'),
67: ('Hasil Pengujian Fungsional (Black-box)', '9 dari 9 kasus uji berhasil (Pass)'),
68: ('Hasil Evaluasi Usability (SUS)', 'Skor SUS rata-rata 88,50: aplikasi mudah digunakan'),
70: ('Diskusi', 'Kekuatan penelitian ada pada cara pengujiannya, bukan sekadar kecocokan dengan data'),
71: ('Keterbatasan Penelitian', 'Keterbatasan disampaikan terbuka; model dipakai untuk membandingkan'),
72: ('Kesimpulan', 'Ketiga tujuan penelitian tercapai'),
73: ('Saran', 'Saran untuk penelitian dan pengembangan selanjutnya'),
}
